In [1]:
import pandas as pd
import numpy as np

In [53]:
cnf_file=pd.read_csv("50var-80claus-satisable.cnf",skiprows=11,header=None,sep=" ",usecols=[0,1,2])

In [62]:
cnf_file.values

array([[ 16,  17,  30],
       [-17,  22,  30],
       [-17, -22,  30],
       [ 16, -30,  47],
       [ 16, -30, -47],
       [-16, -21,  31],
       [-16, -21, -31],
       [-16,  21, -28],
       [-13,  21,  28],
       [ 13, -16,  18],
       [ 13, -18, -38],
       [ 13, -18, -31],
       [ 31,  38,  44],
       [ -8,  31, -44],
       [  8, -12, -44],
       [  8,  12, -27],
       [ 12,  27,  40],
       [ -4,  27, -40],
       [ 12,  23, -40],
       [ -3,   4, -23],
       [  3, -23, -49],
       [  3, -13, -49],
       [-23, -26,  49],
       [ 12, -34,  49],
       [-12,  26, -34],
       [ 19,  34,  36],
       [-19,  26,  36],
       [-30,  34, -36],
       [ 24,  34, -36],
       [-24, -36,  43],
       [  6,  42, -43],
       [-24,  42, -43],
       [ -5, -24, -42],
       [  5,  20, -42],
       [  5,  -7, -20],
       [  4,   7,  10],
       [ -4,  10, -20],
       [  7, -10, -41],
       [-10,  41,  46],
       [-33,  41, -46],
       [ 33, -37, -46],
       [ 32,  33

In [63]:
cnf_data=pd.read_csv("50var-80claus-satisable.cnf",skiprows=11,header=None,sep=" ",usecols=[0,1,2]).values

In [64]:
cnf_data

array([[ 16,  17,  30],
       [-17,  22,  30],
       [-17, -22,  30],
       [ 16, -30,  47],
       [ 16, -30, -47],
       [-16, -21,  31],
       [-16, -21, -31],
       [-16,  21, -28],
       [-13,  21,  28],
       [ 13, -16,  18],
       [ 13, -18, -38],
       [ 13, -18, -31],
       [ 31,  38,  44],
       [ -8,  31, -44],
       [  8, -12, -44],
       [  8,  12, -27],
       [ 12,  27,  40],
       [ -4,  27, -40],
       [ 12,  23, -40],
       [ -3,   4, -23],
       [  3, -23, -49],
       [  3, -13, -49],
       [-23, -26,  49],
       [ 12, -34,  49],
       [-12,  26, -34],
       [ 19,  34,  36],
       [-19,  26,  36],
       [-30,  34, -36],
       [ 24,  34, -36],
       [-24, -36,  43],
       [  6,  42, -43],
       [-24,  42, -43],
       [ -5, -24, -42],
       [  5,  20, -42],
       [  5,  -7, -20],
       [  4,   7,  10],
       [ -4,  10, -20],
       [  7, -10, -41],
       [-10,  41,  46],
       [-33,  41, -46],
       [ 33, -37, -46],
       [ 32,  33

In [109]:
N=10
p=0.3
np.random.seed(0)
np.random.choice(a=[False, True], size=N)

array([False,  True,  True, False,  True,  True,  True,  True,  True,
        True])

In [486]:
def SatCount(booleans,cnf):
    count_good=0
    for clause in cnf:
        # now we have clause like: [4,-1,3], since clause can't have 0 we count from 1 upwards
        # [4,-1,3] means one of 4,3 needs to be true OR 1 needs to be false
        any_good=False
        for clause_num in clause:
            if  booleans[abs(clause_num)-1] == (clause_num > 0):
                any_good=True
                break
        if any_good:
            count_good+=1
    return - count_good

In [186]:

booleans=np.random.choice(a=[False, True], size=50)

SatCount(booleans=booleans,cnf=cnf_data)

-73

In [607]:
import random




class Operator(object):
    def __init__(self, type=None):
        super(Operator, self).__init__()
        self.required_type = type

    def process(self, population):
        raise NotImplementedError()

    def is_compatible(self, operator):
        return  self.required_type == None\
                or operator.required_type == None\
                or operator.required_type == self.required_type

            
class SATGenotype(object):
    def __init__(self, booleans):
        super(SATGenotype, self).__init__()
        self.booleans = list(booleans) # list of ordered bool values which will be used as variables in clauzules
        self.fitness = None # at first will say how many clauzules are correct maybe changed later
        
    def __str__(self):
        return "{0}\nfitness: {1}".format("\n".join(map(str,self.booleans)), self.fitness)
        

import logging

logger = logging.getLogger(__name__)

class AbstractCrossover(Operator):
    def __init__(self, type, size):
        super(AbstractCrossover, self).__init__(type)
        self.__size = size

    def process(self, population):
        parents = list(population)
        for i in range(len(population), self.__size):
            p1, p2 = random.sample(parents, 2)
            genotype = self.cross(p1, p2)
            population.append(genotype)

# previous version
class SATCrossover(AbstractCrossover):
    def __init__(self, size):
        super(SATCrossover, self).__init__(SATGenotype, size)

    def cross(self, p1, p2):
        logger.debug("Crossing:\n{0}\nAND\n{1}".format(p1, p2))
        division = random.randint(1, len(p1.booleans)-2)
        new_booleans = p1.booleans[:division] + p2.booleans[division:]
        return SATGenotype(new_booleans)



In [228]:
bo1=np.random.choice(a=[False, True], size=50)
bo1gen=SATGenotype(bo1)
bo2=np.random.choice(a=[False, True], size=50)
bo2gen=SATGenotype(bo2)

In [233]:
np.array(bo1gen.booleans)

array([False,  True,  True,  True,  True,  True,  True, False,  True,
       False, False, False,  True,  True,  True, False, False,  True,
        True, False, False, False, False, False, False,  True, False,
       False,  True, False,  True, False,  True, False, False, False,
       False,  True,  True,  True,  True,  True,  True, False, False,
       False, False, False,  True, False])

In [234]:
np.array(bo2gen.booleans)

array([False, False,  True,  True,  True,  True, False,  True, False,
        True,  True, False,  True, False, False,  True, False, False,
       False,  True,  True,  True,  True,  True, False, False, False,
       False, False, False,  True,  True, False,  True,  True, False,
        True,  True,  True,  True, False, False, False,  True,  True,
       False, False, False, False,  True])

In [345]:
new_bools=SATCrossover(None).cross(bo1gen,bo2gen).booleans
SatCount(booleans=new_bools,cnf=cnf_data)

-68

In [617]:
# choosing depending on from which array we should take
x = np.arange(50)
condlist = np.random.rand(len(bo1gen.booleans))>0.4
print(condlist)
choicelist = ["0","1"]
print(choicelist)
np.choose(condlist,choicelist)

[False  True  True False False  True False False  True  True  True  True
 False  True  True False False  True  True  True  True  True  True False
 False  True  True  True  True  True  True False False  True  True False
  True False False  True  True  True False  True False  True  True  True
 False  True]
['0', '1']


array(['0', '1', '1', '0', '0', '1', '0', '0', '1', '1', '1', '1', '0',
       '1', '1', '0', '0', '1', '1', '1', '1', '1', '1', '0', '0', '1',
       '1', '1', '1', '1', '1', '0', '0', '1', '1', '0', '1', '0', '0',
       '1', '1', '1', '0', '1', '0', '1', '1', '1', '0', '1'], dtype='|S1')

In [689]:
# now lets take that to action:
class SATCrossover(AbstractCrossover):
    def __init__(self, size, max_fitness, worse_factor=0.4):
        super(SATCrossover, self).__init__(SATGenotype, size)
        self.max_fitness=max_fitness
        self.worse_factor=worse_factor # probability of taking worse fitnessed value

    def cross(self, p1, p2):
        logger.debug("Crossing:\n{0}\nAND\n{1}".format(p1, p2))
        # 1. chosse better fitness
        if p2.fitness > p1.fitness:
            p1,p2 = p2,p1 # swap
        # p1 has better fitness
        # 2. make array of True,False which will determine if we take value from p1 or p2
        choose_array = np.random.rand(len(bo1gen.booleans))<self.worse_factor
        # 3. choose values from p1 or p2 depending on choose_array
        new_booleans = np.choose(choose_array,[p1.booleans,p2.booleans])
        return SATGenotype(new_booleans)


In [690]:
bo1gen.fitness=-SatCount(bo1gen.booleans,cnf_data)
print(bo1gen.fitness)
bo2gen.fitness=-SatCount(bo2gen.booleans,cnf_data)
print(bo2gen.fitness)

69
78


In [847]:
# max fitness = 80 since 80 clauses
new_bools=SATCrossover(None,80,0.1).cross(bo1gen,bo2gen).booleans
print(new_bools)
SatCount(booleans=new_bools,cnf=cnf_data)

[False, False, True, True, False, False, False, True, True, False, False, False, False, True, True, True, True, True, False, True, False, True, True, True, True, False, True, False, True, True, False, False, False, True, False, False, False, True, True, True, True, True, True, False, True, False, True, True, True, True]


-77

# looks ok

In [849]:
cnf_data.max()

50